/**
 * BYOK (bring your own key) provider calls.
 *
 * What was removed and why: this module used to export
 * `generateSmartLocalPharmacologyResponse`, a five-branch `if/else` over
 * keywords that returned hardcoded HTML. When no API key was present the app
 * called it and presented the output as a "klinik sentez motoru" analysis,
 * complete with specific dosing instructions ("statini 20:30-21:30 arasında
 * alınız") and invented precision ("~%40 oranında azaltır").
 *
 * A keyword match is not an inference engine, and handing a patient timing
 * instructions generated by `q.includes("saat")` is not acceptable in a
 * medication app. There is now no fallback: without a key the AI panel stays
 * switched off and says so. See `src/features/aiLab.ts`.
 */

import type { ByokProvider } from "../types/index.ts";

export const SYSTEM_INSTRUCTION =
  "Sen MedWise farmakoloji çalışma asistanısın. Sorulara kanıta dayalı, net ve " +
  "sade Türkçe yanıt ver. Kesin doz talimatı verme; bunun yerine hastayı " +
  "hekimine veya eczacısına yönlendir. Emin olmadığın bilgiyi uydurma, " +
  "bilmiyorsan bilmediğini söyle.";

/** Model identifiers, kept here so they are updated in exactly one place. */
export const PROVIDER_MODELS: Record<ByokProvider, string> = {
  gemini: "gemini-2.0-flash",
  gpt4o: "gpt-4o",
  claude: "claude-sonnet-5",
};

export const PROVIDER_LABELS: Record<ByokProvider, string> = {
  gemini: "Google Gemini",
  gpt4o: "OpenAI GPT-4o",
  claude: "Anthropic Claude",
};

/** Thrown when a provider rejects the request, so the UI can show the reason. */
export class ProviderError extends Error {
  constructor(
    public readonly provider: ByokProvider,
    public readonly status: number,
    message: string
  ) {
    super(message);
    this.name = "ProviderError";
  }
}

export async function callGeminiApi(
  prompt: string,
  key: string,
  endpoint: string = import.meta.env.VITE_GEMINI_ENDPOINT ||
    "https://generativelanguage.googleapis.com/v1beta/models"
): Promise<string> {
  const url = `${endpoint}/${PROVIDER_MODELS.gemini}:generateContent?key=${encodeURIComponent(key)}`;
  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: SYSTEM_INSTRUCTION }] },
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    }),
  });

  if (!resp.ok) {
    throw new ProviderError("gemini", resp.status, `Gemini ${resp.status} ${resp.statusText}`);
  }

  const data = await resp.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new ProviderError("gemini", resp.status, "Gemini boş yanıt döndürdü.");
  return text;
}

export async function callOpenAiApi(
  prompt: string,
  key: string,
  endpoint: string = import.meta.env.VITE_OPENAI_ENDPOINT ||
    "https://api.openai.com/v1/chat/completions"
): Promise<string> {
  const resp = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${key}`,
    },
    body: JSON.stringify({
      model: PROVIDER_MODELS.gpt4o,
      messages: [
        { role: "system", content: SYSTEM_INSTRUCTION },
        { role: "user", content: prompt },
      ],
    }),
  });

  if (!resp.ok) {
    throw new ProviderError("gpt4o", resp.status, `OpenAI ${resp.status} ${resp.statusText}`);
  }

  const data = await resp.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new ProviderError("gpt4o", resp.status, "OpenAI boş yanıt döndürdü.");
  return text;
}

export async function callClaudeApi(prompt: string, key: string): Promise<string> {
  const resp = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": key,
      "anthropic-version": "2023-06-01",
      // Correct header name. The previous build sent "dangerously-allow-browser",
      // which the API does not recognise, so every browser call failed.
      "anthropic-dangerous-direct-browser-access": "true",
    },
    body: JSON.stringify({
      model: PROVIDER_MODELS.claude,
      max_tokens: 1024,
      system: SYSTEM_INSTRUCTION,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!resp.ok) {
    throw new ProviderError("claude", resp.status, `Claude ${resp.status} ${resp.statusText}`);
  }

  const data = await resp.json();
  const text = data.content?.[0]?.text;
  if (!text) throw new ProviderError("claude", resp.status, "Claude boş yanıt döndürdü.");
  return text;
}

/** Dispatches to the configured provider. */
export function callProvider(provider: ByokProvider, prompt: string, key: string): Promise<string> {
  switch (provider) {
    case "gemini":
      return callGeminiApi(prompt, key);
    case "gpt4o":
      return callOpenAiApi(prompt, key);
    case "claude":
      return callClaudeApi(prompt, key);
  }
}
